import type { UserRole, Permission, DummyUser } from "@/types/auth";
import { dummyUsers } from "@/data/auth";

// Re-export so consumers (e.g. lib/auth-server) can import UserRole from here.
export type { UserRole } from "@/types/auth";

/**
 * TASK-73 — Single source of truth for DEFAULT role → permission grants.
 * Every permission check ultimately resolves through this map (static)
 * layered with DB role grants + per-user overrides (lib/security/permissions).
 *
 * CEO / ADMIN are super-users (SYSTEM_ADMIN + every granular permission).
 * New default roles (Manager, Marketing, Sales, HR, Support, Editor) get the
 * minimum viable grant for their function. CUSTOM roles start empty — their
 * permissions are 100% DB-driven.
 */
const ALL: Permission[] = [
  "VIEW_DASHBOARD", "VIEW_TEAM", "MANAGE_TEAM", "APPROVE_WORK",
  "VIEW_USERS", "MANAGE_USERS", "MANAGE_ROLES",
  "VIEW_SOCIAL", "MANAGE_SOCIAL", "SOCIAL_CONNECT", "SOCIAL_DISCONNECT",
  "VIEW_INBOX", "REPLY_INBOX", "ASSIGN_CONVERSATION", "MANAGE_CONVERSATION",
  "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT", "VIEW_ALL_CONVERSATIONS", "MANAGE_SPAM", "MANAGE_INBOX_SETTINGS",
  "VIEW_MEDIA", "MANAGE_MEDIA", "MEDIA_UPLOAD", "MEDIA_DELETE",
  "VIEW_AI", "MANAGE_AI",
  "VIEW_ANALYTICS",
  "VIEW_SCHEDULER", "VIEW_PUBLISHING",
  "VIEW_SETTINGS", "MANAGE_SETTINGS",
  "VIEW_SECURITY", "MANAGE_SECURITY",
  "VIEW_BACKUP", "MANAGE_BACKUP",
  "VIEW_NOTIFICATIONS", "MANAGE_NOTIFICATIONS",
  "SYSTEM_ADMIN",
];

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  CEO: [...ALL],
  ADMIN: [...ALL],
  MANAGER: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "MANAGE_TEAM", "APPROVE_WORK",
    "VIEW_USERS", "VIEW_SOCIAL", "MANAGE_SOCIAL", "SOCIAL_CONNECT", "SOCIAL_DISCONNECT",
    "VIEW_INBOX", "REPLY_INBOX", "ASSIGN_CONVERSATION", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT", "VIEW_ALL_CONVERSATIONS", "MANAGE_SPAM", "MANAGE_INBOX_SETTINGS",
    "VIEW_MEDIA", "MANAGE_MEDIA", "MEDIA_UPLOAD", "MEDIA_DELETE",
    "VIEW_AI", "MANAGE_AI", "VIEW_ANALYTICS",
    "VIEW_SETTINGS", "VIEW_SECURITY", "VIEW_BACKUP",
    "VIEW_NOTIFICATIONS", "MANAGE_NOTIFICATIONS",
  ],
  MARKETING_MANAGER: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "MANAGE_TEAM", "APPROVE_WORK",
    "VIEW_SOCIAL", "MANAGE_SOCIAL", "SOCIAL_CONNECT", "SOCIAL_DISCONNECT",
    "VIEW_INBOX", "REPLY_INBOX", "ASSIGN_CONVERSATION", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT", "VIEW_ALL_CONVERSATIONS", "MANAGE_SPAM",
    "VIEW_MEDIA", "MANAGE_MEDIA", "MEDIA_UPLOAD", "MEDIA_DELETE",
    "VIEW_AI", "VIEW_ANALYTICS",
    "VIEW_SETTINGS", "VIEW_NOTIFICATIONS",
  ],
  MARKETING: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "SOCIAL_CONNECT",
    "VIEW_INBOX", "REPLY_INBOX", "ASSIGN_CONVERSATION", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT",
    "VIEW_MEDIA", "MEDIA_UPLOAD", "VIEW_AI", "VIEW_ANALYTICS", "VIEW_NOTIFICATIONS",
  ],
  SALES: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "VIEW_MEDIA", "VIEW_AI",
    "VIEW_INBOX", "REPLY_INBOX", "ASSIGN_CONVERSATION", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT",
    "VIEW_ANALYTICS", "VIEW_NOTIFICATIONS", "VIEW_SETTINGS",
  ],
  HR: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_USERS", "MANAGE_USERS",
    "VIEW_NOTIFICATIONS", "VIEW_SETTINGS", "VIEW_SECURITY",
  ],
  SUPPORT: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_USERS", "VIEW_SOCIAL", "VIEW_MEDIA",
    "VIEW_INBOX", "REPLY_INBOX", "ASSIGN_CONVERSATION", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT", "MANAGE_SPAM",
    "VIEW_NOTIFICATIONS", "VIEW_SETTINGS",
  ],
  EDITOR: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "SOCIAL_CONNECT",
    "VIEW_INBOX", "REPLY_INBOX", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT",
    "VIEW_MEDIA", "MEDIA_UPLOAD", "MEDIA_DELETE", "VIEW_AI", "VIEW_ANALYTICS",
    "VIEW_NOTIFICATIONS",
  ],
  MARKETING_TEAM: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "SOCIAL_CONNECT",
    "VIEW_INBOX", "REPLY_INBOX", "MANAGE_CONVERSATION", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT",
    "VIEW_MEDIA", "MEDIA_UPLOAD", "VIEW_AI", "VIEW_ANALYTICS", "VIEW_NOTIFICATIONS",
  ],
  CONTENT_CREATOR: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "VIEW_MEDIA", "MEDIA_UPLOAD",
    "VIEW_INBOX", "REPLY_INBOX", "ADD_INTERNAL_NOTE", "USE_AI_ASSISTANT",
    "VIEW_AI", "VIEW_ANALYTICS", "VIEW_NOTIFICATIONS",
  ],
  ANALYST: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "VIEW_MEDIA", "VIEW_AI",
    "VIEW_INBOX", "USE_AI_ASSISTANT", "VIEW_ALL_CONVERSATIONS",
    "VIEW_ANALYTICS", "VIEW_NOTIFICATIONS",
  ],
  VIEWER: [
    "VIEW_DASHBOARD", "VIEW_TEAM", "VIEW_SOCIAL", "VIEW_MEDIA",
    "VIEW_INBOX",
    "VIEW_ANALYTICS", "VIEW_NOTIFICATIONS",
  ],
  CUSTOM: [], // permissions fully DB-driven via Role/UserPermissionOverride
};

export function getUserPermissions(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(userRole: UserRole, permission: Permission): boolean {
  return getUserPermissions(userRole).includes(permission);
}

export function authenticate(email: string, password: string): DummyUser | null {
  return dummyUsers.find((u) => u.email === email && u.password === password) ?? null;
}

export function toSessionUser(user: DummyUser) {
  const { password, ...rest } = user;
  return rest;
}
