"use client";

import { motion } from "framer-motion";
import { Copy, Save, RefreshCcw, Share } from "lucide-react";

type AiOutputProps = {
  content: string;
};

export default function AiOutput({ content }: AiOutputProps) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
      <div className="text-xs font-semibold uppercase tracking-wider text-white/50">Generated by K2Kai AI</div>
      <div className="mt-3 text-sm text-white/80">{content}</div>
      <div className="mt-4 flex flex-wrap gap-2">
        <motion.button whileHover={{ y: -1, scale: 1.02 }} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.05] px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-white/[0.12]">
          <Copy className="h-3.5 w-3.5" strokeWidth={1.8} /> Copy
        </motion.button>
        <motion.button whileHover={{ y: -1, scale: 1.02 }} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.05] px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-white/[0.12]">
          <Save className="h-3.5 w-3.5" strokeWidth={1.8} /> Save
        </motion.button>
        <motion.button whileHover={{ y: -1, scale: 1.02 }} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.05] px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-white/[0.12]">
          <RefreshCcw className="h-3.5 w-3.5" strokeWidth={1.8} /> Regenerate
        </motion.button>
        <motion.button whileHover={{ y: -1, scale: 1.02 }} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.05] px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-white/[0.12]">
          <Share className="h-3.5 w-3.5" strokeWidth={1.8} /> Share
        </motion.button>
      </div>
    </div>
  );
}
